apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default-profile # {"$ref":"#/definitions/io.k8s.cli.substitutions.namespace"}
# N.B. Don't set common labels; kustomzie will use that to update selectors which will break things.
resources:
- application.yaml
- notebook.yaml
- pvc.yaml
- service.yaml
- virtual_service.yaml
